### ISSUE TITLE
conda dependencies are out of date

### ISSUE THREAD

**Issue by analog-cbarber** [conda-forge/beanie-feedstock#38]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

As of 1.25.0 The current [pyproject.toml](https://github.com/roman-right/beanie/blob/main/pyproject.toml) dependencies for beanie are:

```toml
dependencies = [
    "pydantic>=1.10,<3.0",
    "motor>=2.5.0,<4.0.0",
    "click>=7",
    "toml",
    "lazy-model==0.2.0",
    "typing-extensions>=4.7; python_version < '3.11'",
]
```

but the [conda recipe](https://github.com/conda-forge/beanie-feedstock/blob/main/recipe/meta.yaml) still has

```yaml
requirements:
  host:
    - pip
    - flit-core
    - python >=3.7
  run:
    - click >=7
    - motor >=2.5,<4.0
    - pydantic >=1.10.0,<2
    - python >=3.7
    - toml
    - lazy-model >=0.1.0
```

As a result, the conda beanie pckage cannot be used with pydantic 2.*

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```
